# Generated by Django 4.2.20 on 2025-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_newsletter_test", "0002_simplepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrecipients",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
